### ISSUE TITLE
v1.3.2 and latest commit from master branch no longer build on Arch Linux

### ISSUE THREAD

**Issue by FabioLolix** [pop-os/popsicle#208]
Hello, I'm the maintainer of the AUR pkgbuilds popsicle and popsicle-git

**Distribution (run `cat /etc/os-release`):**
 
```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

v1.3.2 and latest commit from master branch

**Issue/Bug Description:**

Both the last stable release and last commit no longer build on Arch Linux, this has been reported to me today and have confirmed the issue

Rust is at v1.74.1

v1.3.2
```
   Compiling futures_codec v0.4.1
error: failed to run custom build command for `loopdev v0.4.0`

Caused by:
  process didn't exit successfully: `/home/fabio/Dev/Github/PKGBUILD-AUR_fix/p/popsicle/src/popsicle/target/release/build/loopdev-13cf59a56d32320a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/fabio/Dev/Github/PKGBUILD-AUR_fix/p/popsicle/src/popsicle/vendor/proc-macro2/src/fallback.rs:791:9:
  "enum_(unnamed_at_/usr/include/linux/loop_h_16_1)" is not a valid Ident
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:107: target/release/popsicle-gtk] Error 101
==> ERROR: A failure occurred in build().
```

v1.3.2.r4.g22c34ae
```
   Compiling num_enum v0.5.11
error: failed to run custom build command for `loopdev v0.4.0`

Caused by:
  process didn't exit successfully: `/home/fabio/Dev/Github/PKGBUILD-AUR_fix/p/popsicle-git/src/popsicle/target/release/build/loopdev-13cf59a56d32320a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/fabio/Dev/Github/PKGBUILD-AUR_fix/p/popsicle-git/src/popsicle/vendor/proc-macro2/src/fallback.rs:791:9:
  "enum_(unnamed_at_/usr/include/linux/loop_h_16_1)" is not a valid Ident
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:107: target/release/popsicle-gtk] Error 101
==> ERROR: A failure occurred in build().
```

**Steps to reproduce (if you know):**

Install Arch Linux
sudo pacman -Syyu base-devel git
git clone https://aur.archlinux.org/popsicle.git
cd popsicle
makepkg -s

popsicle-git on AUR still have old build instructions at the moment, realized now when checking, I have updated it locally for now

**Expected behavior:**

pkgbuilds build fine

**Other Notes:**

**Comment by tormeh** [comment]
Similar problem for Nix: https://github.com/NixOS/nixpkgs/issues/269914

**Comment by mmstick** [comment]
I'll check it out. Probably just needs a dependency update

**Comment by tormeh** [comment]
Indeed, a similar problem seems to have been fixed for Zenith with a dep update: https://github.com/bvaisvil/zenith/pull/135

**Comment by yochananmarqos** [comment]
Still doesn't build:

```
   Compiling loopdev v0.4.0
error: failed to run custom build command for `loopdev v0.4.0`

Caused by:
  process didn't exit successfully: `/build/popsicle/src/popsicle/target/release/build/loopdev-2def6cd8e1102345/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /build/popsicle/src/popsicle/vendor/bindgen/src/ir/context.rs:878:9:
  "enum_(unnamed_at_/usr/include/linux/loop_h_16_1)" is not a valid Ident
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:107: target/release/popsicle-gtk] Error 101

```

**Comment by FabioLolix** [comment]
Confirm is not resolved yet

**Comment by mmstick** [comment]
Depends on https://github.com/mdaffin/loopdev/issues/62 being resolved

**Comment by mmstick** [comment]
Try building from the branch at https://github.com/pop-os/popsicle/pull/210

**Comment by yochananmarqos** [comment]
Yes, it builds now.

**Comment by FabioLolix** [comment]
It build and work
